# Инвентарь — список серверов, которыми управляет Ansible.
# Серверы объединяются в группы: плейбук адресуется группе,
# и добавление второго сервера в группу = деплой на оба.
all:
  children:
    webservers:          # имя группы (его использует плейбук)
      hosts:
        web1:            # псевдоним сервера, для людей и логов
          ansible_host: 158.160.16.86   # реальный адрес
          ansible_user: koolinio        # под кем заходить по ssh
          # ssh-ключ не указываем: возьмётся дефолтный
          # ~/.ssh/id_ed25519 — тот же, что при ручном ssh
          ansible_python_interpreter: /usr/bin/python3
          server_message: "Вас обслуживает web1"
          app_ports: []
          internal_ip: 10.129.0.33
          app_scrape_target: "app:3000"
        web2:
          ansible_host: 158.160.21.148   # реальный адрес
          ansible_user: koolinio        # под кем заходить по ssh
          ansible_python_interpreter: /usr/bin/python3  
          server_message: "Вас обслуживает web2"
          app_scrape_target: "10.129.0.24:3000"
          internal_ip: 10.129.0.24
          app_ports:
            - "10.129.0.24:3000:3000"
    balancers:
      hosts:
        web1:            